### ISSUE TITLE
PostGIS data for Bonn, Germany not available for download

### ISSUE THREAD

**Issue by yhrchan** [go-spatial/tegola-docs#28]
The sample data file is not available for download in the Getting Started with Tegola tutorials. Can someone have a look? Thanks!

https://s3-us-west-2.amazonaws.com/tegola/bonn_osm.sql.tgz

<Error>
<Code>AllAccessDisabled</Code>
<Message>All access to this object has been disabled</Message>
<RequestId>CACAD1B82CBED110</RequestId>
<HostId>
dwlee2oMqqcaiy8AVx4ZJ6bLhcyQcQcthiMKVLwRDmMbMe7/6pPCpGtjajjEYvpbr50oE6787nw=
</HostId>
</Error>

**Comment by ARolek** [comment]
Thanks for the report. I just pushed a fix. Docs will rebuild and deploy automatically.
