### ISSUE TITLE
Code blocks use poor colors

### ISSUE THREAD

**Issue by freezurbern** [go-spatial/tegola-docs#62]
**Link:**
https://tegola.io/documentation/cache-seeding-and-purging/

The code blocks have text the same color as the background.
In the `<pre>` tag, the text color should not be set as light grey:
```html
<div class="highlight">
<pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4">
<code class="language-text" data-lang="text">
Available Commands:
  seed        seed tiles to the cache
  purge       purge tiles from the cache
</code></pre></div>
```

![image](https://github.com/go-spatial/tegola-docs/assets/6363417/ee0ae433-7a4c-45e3-9d0b-69ffc4c43303)

**Screenshot:**
![image](https://github.com/go-spatial/tegola-docs/assets/6363417/db22e91c-96d7-4b02-a1f1-05ec7ecfe642)

**Comment by ARolek** [comment]
@freezurbern well that's pretty ugly. I will look into getting this addressed. Thanks for the report!

**Comment by freezurbern** [comment]
I was curious, and it looks like you may be able to remove the `text` hint from the affected blocks:
https://github.com/go-spatial/tegola-docs/blob/15990e239b80e64fb025d81ce34c01f9f49bbe83/content/documentation/cache-seeding-and-purging.md?plain=1#L31-L40

Because later in the same document, a bare ` ``` ` is used without issue:
https://github.com/go-spatial/tegola-docs/blob/15990e239b80e64fb025d81ce34c01f9f49bbe83/content/documentation/cache-seeding-and-purging.md?plain=1#L105-L112

**Comment by ARolek** [comment]
@freezurbern I just pushed up a fix so it should deploy shortly. Thanks for raising this issue and doing the associated investigation!
